## The Data Scientist's Toolbox Project


#### PROMPT 1 
1. Install R 
2. Install Rstudio
3. Open Rstudio and take a screenshot
4. Upload a screenshot of Rstudio open on your screen using one of these formats: png, jpg, gif, pdf

Be careful not to have personally identifiable or important information visible in the screen shot!


#### PROMPT 2 
1. Set up a Github account (you may use your own name or a pseudonym).
2. Create a repo called datasciencecoursera
3. Copy and paste the link to your GitHub account (or a direct link to your datasciencecoursera repo)


#### PROMPT 3
1. Create a text file called HelloWorld.md
2. Add the line "## This is a markdown file" (without the quotation marks) to the document
3. Push the document to the datasciencecoursera repo you created on Github
4. Submit the link to the HelloWorld.md file on your Github repo. 


#### PROMPT 4
1. Fork the data sharing repository here: https://github.com/jtleek/datasharing
2. Copy and paste the link to the forked repository on your Github account. 
